# Generated by Django 4.2.7 on 2023-11-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('plan', models.FileField(upload_to='pdfs/')),
                ('category', models.CharField(choices=[('Liscence', 'Liscence'), ('Ingenieurie', 'Ingenieurie'), ('Cycle préparatoire integré', 'Cycle préparatoire integré'), ('Mastere de recherche', 'Mastere de recherche'), ('Mastere professionelle', 'Mastere professionelle')], max_length=255)),
            ],
        ),
    ]
