# Generated by Django 4.2.7 on 2023-11-23 18:13

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='description',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
