# Generated by Django 4.2.7 on 2023-11-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='description',
            field=models.TextField(),
        ),
    ]
