# Generated by Django 4.2.7 on 2023-11-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_formation_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the department', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='A brief description of the department', null=True)),
                ('leader_of_department', models.CharField(help_text='The leader of the department', max_length=100)),
                ('established_date', models.DateField(blank=True, help_text='The date when the department was established')),
            ],
        ),
    ]
