# Generated by Django 4.2.3 on 2023-12-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='actualite_images/')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Isimm', 'Isimm'), ('Formation', 'Formation'), ('Recherche', 'Recherche'), ('Entreprise', 'Entreprise'), ('Contact', 'Contact')], max_length=20)),
            ],
        ),
    ]
