# Generated by Django 4.2.7 on 2023-12-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_actualite'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='title',
            field=models.CharField(default='nouvelle actualité', max_length=255),
            preserve_default=False,
        ),
    ]
