# Generated by Django 4.2.3 on 2023-12-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_alter_formation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('Informatique', 'Informatique'), ('Mathematique', 'Mathematique'), ('Technologie', 'Technologie')], max_length=255),
        ),
    ]
