# Generated by Django 4.2.3 on 2024-01-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_alter_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='target_audience',
            field=models.CharField(default='tous', max_length=50),
        ),
    ]
