# Generated by Django 5.0.1 on 2024-01-25 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_rename_speciality_groupe_formation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupe',
            old_name='speciality_name',
            new_name='formation_name',
        ),
    ]
