# Generated by Django 5.0.1 on 2024-02-07 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_groupe_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2023, 2, 1)),
            preserve_default=False,
        ),
    ]
