# Generated by Django 5.0.1 on 2024-02-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_groupe_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='emploi',
            field=models.FileField(default=None, upload_to='emplois/'),
        ),
    ]
