# Generated by Django 5.0.1 on 2024-02-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_groupe_emploi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='emploi',
            field=models.FileField(blank=True, default=None, null=True, upload_to='emplois/'),
        ),
    ]
