# Generated by Django 4.2.3 on 2024-02-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignant', '0002_alter_enseignant_department_and_more'),
        ('mainApp', '0018_alter_groupe_emploi'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='enseignants',
            field=models.ManyToManyField(related_name='groupes', to='enseignant.enseignant'),
        ),
    ]
