# Generated by Django 5.0.1 on 2024-03-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignant', '0002_alter_enseignant_department_and_more'),
        ('mainApp', '0019_groupe_enseignants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('en attente', 'en attente'), ('en cours', 'en cours'), ('refusé', 'refusé'), ('prêt', 'Prêt')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='groupe',
            name='enseignants',
            field=models.ManyToManyField(blank=True, related_name='groupes', to='enseignant.enseignant'),
        ),
    ]
