# Generated by Django 5.0.1 on 2024-03-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0020_attestation_alter_groupe_enseignants'),
    ]

    operations = [
        migrations.AddField(
            model_name='attestation',
            name='cin',
            field=models.CharField(default='20', max_length=50),
        ),
        migrations.AlterField(
            model_name='attestation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='attestation',
            name='state',
            field=models.CharField(choices=[('en attente', 'en attente'), ('en cours', 'en cours'), ('refusé', 'refusé'), ('prêt', 'Prêt')], default='en attente', max_length=20),
        ),
    ]
