# Generated by Django 4.2.3 on 2023-12-23 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainApp', '0009_alter_department_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cin', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=50)),
                ('level', models.CharField(blank=True, max_length=50)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('phoneNumber', models.CharField(blank=True, max_length=15)),
                ('datebirth', models.DateField(blank=True, null=True)),
                ('parentfname', models.CharField(blank=True, max_length=100)),
                ('parentlname', models.CharField(blank=True, max_length=100)),
                ('ImageProfil', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('groupTD', models.CharField(blank=True, max_length=50)),
                ('codePostal', models.CharField(blank=True, max_length=10)),
                ('speciality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.formation')),
            ],
        ),
    ]
