# Generated by Django 4.2.3 on 2023-12-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='speciality_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
