# Generated by Django 4.2.3 on 2023-12-23 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsApp', '0002_student_speciality_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='speciality',
            new_name='speciality_id',
        ),
    ]
