# Generated by Django 4.2.3 on 2023-12-23 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsApp', '0003_rename_speciality_student_speciality_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='speciality_id',
            new_name='speciality',
        ),
    ]
