# Generated by Django 5.0 on 2023-12-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsApp', '0004_rename_speciality_id_student_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='first_check',
            field=models.BooleanField(default=False),
        ),
    ]
